from typing import Protocol, List
from datetime import date, time
from uuid import UUID

class CacheClient(Protocol):
    async def get(self, key: str): ...
    async def setex(self, name: str, time: int, value: str): ...

class AvailabilityRepoInterface(Protocol):
    async def get_restaurant(self): ...
    async def get_table_types(self, restaurant_id: UUID, table_type_id: UUID = None): ...
    async def get_occupied_seats(self, target_date: date, target_time: time): ...