# Generated by Django 6.0.5 on 2026-05-21 23:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created', help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified', help_text='Fecha y hora de la última modificación')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=20)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': '"content"."reservation"',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created', help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified', help_text='Fecha y hora de la última modificación')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', help_text='Ej: Europe/Madrid o America/La_Paz', max_length=50)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': '"content"."restaurant"',
            },
        ),
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created', help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified', help_text='Fecha y hora de la última modificación')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, help_text='Alergias o peticiones especiales', null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'db_table': '"content"."reservation_guest"',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.restaurant'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created', help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified', help_text='Fecha y hora de la última modificación')),
                ('date', models.DateField(help_text='Fecha en la que este menú está disponible')),
                ('course', models.CharField(help_text='Ej: Starter, Main, Dessert', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allergens', models.JSONField(blank=True, default=list, help_text='Lista de strings con alérgenos')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='reservations.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': '"content"."menu_item"',
            },
        ),
        migrations.CreateModel(
            name='TableType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created', help_text='Fecha y hora de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modified', help_text='Fecha y hora de la última modificación')),
                ('name', models.CharField(help_text='Ej: Mesa Compartida, Barra', max_length=100)),
                ('seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_types', to='reservations.restaurant')),
            ],
            options={
                'verbose_name': 'Table Type',
                'verbose_name_plural': 'Table Types',
                'db_table': '"content"."table_type"',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.tabletype'),
        ),
    ]
